---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/' # Location of the package files
    schedule:
      interval: 'daily' # Check for updates daily
    groups:
      github-dependencies:
        patterns:
          - '*'
    cooldown:
      default-days: 7
