---
name: ğŸ¥‡ First Interaction

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  welcome:
    name: ğŸ‘½ Greetings Earthling
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘‹ğŸ½ Welcome Message
        uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d
        with:
          issue_message: |
            Thanks for opening this issue! We appreciate your contribution.
          pr_message: |
            ğŸ‰ Welcome to our project, @{{ github.actor }}! Thank you for contributing!
            Weâ€™re glad to have you here. If you have any questions, feel free to ask!
          repo_token: ${{ secrets.GITHUB_TOKEN }}
